// ============================================================
// HOMEFIX AI — Constants & Enums
// ============================================================

const BOOKING_STATUS = {
  PENDING: 'PENDING',           // Khách vừa đặt, chờ Admin xác nhận
  CONFIRMED: 'CONFIRMED',       // Admin xác nhận, chờ gán thợ
  ASSIGNED: 'ASSIGNED',         // Đã gán thợ, chờ thợ nhận
  IN_PROGRESS: 'IN_PROGRESS',   // Thợ đã nhận và đang di chuyển/bắt đầu
  INSPECTING: 'INSPECTING',     // Thợ đang khảo sát, kiểm tra thiết bị
  QUOTED: 'QUOTED',             // Thợ đã gửi báo giá, chờ khách duyệt
  COMPLETING: 'COMPLETING',     // Khách duyệt báo giá, thợ đang sửa
  COMPLETED: 'COMPLETED',       // Hoàn thành sửa chữa
  CANCELLED: 'CANCELLED',       // Đã hủy
};

// Luồng chuyển trạng thái hợp lệ
const BOOKING_STATUS_TRANSITIONS = {
  [BOOKING_STATUS.PENDING]:      [BOOKING_STATUS.CONFIRMED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.CONFIRMED]:    [BOOKING_STATUS.ASSIGNED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.ASSIGNED]:     [BOOKING_STATUS.IN_PROGRESS, BOOKING_STATUS.CONFIRMED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.IN_PROGRESS]:  [BOOKING_STATUS.INSPECTING, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.INSPECTING]:   [BOOKING_STATUS.QUOTED, BOOKING_STATUS.COMPLETING, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.QUOTED]:       [BOOKING_STATUS.COMPLETING, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.COMPLETING]:   [BOOKING_STATUS.COMPLETED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.COMPLETED]:    [], // Trạng thái cuối, không chuyển tiếp
  [BOOKING_STATUS.CANCELLED]:    [], // Trạng thái cuối, không chuyển tiếp
};

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
};

const PAYMENT_METHOD = {
  VNPAY: 'VNPAY',
  CASH: 'CASH',
};

const QUOTATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};

const COMPLAINT_STATUS = {
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
};

const NOTIFICATION_TYPE = {
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  QUOTATION: 'QUOTATION',
  REVIEW: 'REVIEW',
  COMPLAINT: 'COMPLAINT',
  SYSTEM: 'SYSTEM',
};

const ROLES = {
  CUSTOMER: 'CUSTOMER',
  TECHNICIAN: 'TECHNICIAN',
  ADMIN: 'ADMIN',
};

const SKILL_LEVEL = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  EXPERT: 'EXPERT',
};

const SENTIMENT = {
  POSITIVE: 'POSITIVE',
  NEUTRAL: 'NEUTRAL',
  NEGATIVE: 'NEGATIVE',
};

// Business rules constants
const BUSINESS_RULES = {
  MAX_ADDRESSES_PER_USER: 5,
  OTP_EXPIRY_MINUTES: 5,
  OTP_MAX_ATTEMPTS: 5,
  OTP_COOLDOWN_SECONDS: 60,
  MIN_BOOKING_ADVANCE_HOURS: 24,    // Đặt trước ít nhất 24h
  BOOKING_TIME_START: '08:00',       // Ca làm việc bắt đầu
  BOOKING_TIME_END: '18:00',         // Ca làm việc kết thúc
  MIN_RATING: 1,
  MAX_RATING: 5,
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 50,
  DEFAULT_TECH_PASSWORD: 'HomeFix@2026',
  SALT_ROUNDS: 10,
  JWT_EXPIRY: '7d',
};

// Status mà Customer có thể tự hủy
const CUSTOMER_CANCELLABLE_STATUSES = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.CONFIRMED,
];

// Status mà Admin có thể hủy
const ADMIN_CANCELLABLE_STATUSES = [
  BOOKING_STATUS.PENDING,
  BOOKING_STATUS.CONFIRMED,
  BOOKING_STATUS.ASSIGNED,
  BOOKING_STATUS.IN_PROGRESS,
  BOOKING_STATUS.INSPECTING,
  BOOKING_STATUS.QUOTED,
  BOOKING_STATUS.COMPLETING,
];

module.exports = {
  BOOKING_STATUS,
  BOOKING_STATUS_TRANSITIONS,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  QUOTATION_STATUS,
  COMPLAINT_STATUS,
  NOTIFICATION_TYPE,
  ROLES,
  SKILL_LEVEL,
  SENTIMENT,
  BUSINESS_RULES,
  CUSTOMER_CANCELLABLE_STATUSES,
  ADMIN_CANCELLABLE_STATUSES,
};
